version: 2.1


executors:
  node:
    docker:
      - image: circleci/node:13.8.0
  python:
    docker:
      - image: python:3.9.0-alpine
  aws:
    docker:
      - image: amazon/aws-cli
jobs:
  create-server:
    executor: aws
    steps:
      - add_ssh_keys:
          fingerprints: ["d3:39:d3:16:84:f9:c9:1c:46:78:a1:f9:ab:5c:71:6f"]
    
      - run:
          name: Deploy backend infrastructure
          working_directory: ./.circleci
          command: |
            aws cloudformation deploy \
              --template-file server.yml \
              --stack-name "MLearning-MicroService-${CIRCLE_WORKFLOW_ID:0:7}" \
              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
              --tags project=MLearning-MicroService-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: Save backend URL in memstash
          command: |
            SERVER_IP=$(aws ec2 describe-instances \
              --query 'Reservations[*].Instances[*].PublicIpAddress' \
              --filters "Name=tag:project,Values=MLearning-MicroService-${CIRCLE_WORKFLOW_ID:0:7}" \
              --output text)
            

            
            curl -H "Content-Type: text/plain" -H "token: 1e288415-cfc8-4a0a-a23c-087eb7cd7678" --request PUT --data "http://$SERVER_IP" https://api.memstash.io/values/SERVER_URL
            IP=$(curl -H "Content-Type: text/plain" -H "token: 1e288415-cfc8-4a0a-a23c-087eb7cd7678"  --request GET https://api.memstash.io/values/SERVER_URL)
            echo "${IP}"
            
            

workflows:
    default:
      jobs:
        - create-server
